import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { buildMetadata } from "@/lib/seo/metadata";
import { breadcrumbSchema } from "@/lib/seo/schema";
import { JsonLd } from "@/lib/seo/JsonLd";
import { PageHeader } from "@/components/shared/PageHeader";
import { Section } from "@/components/layout/Section";

const articles = {
  "melhor-creatina-custo-beneficio-2026": { title: "Melhor Creatina Custo-Benefício em 2026", description: "Como comparar creatinas pelo preço por dose, nota e transparência do rótulo.", intro: "A melhor compra depende do conjunto, não apenas do menor preço. O ranking de Creatina do SupleScore reúne os produtos e deixa os critérios visíveis para facilitar a decisão.", sections: [["Comece pelo custo por dose", "Compare o preço da embalagem com a quantidade de porções. Essa métrica coloca produtos de tamanhos diferentes na mesma base e evita escolher apenas pela etiqueta mais barata."], ["Confira a composição", "Verifique a forma declarada, a quantidade por porção e as informações do rótulo. A comparação fica mais útil quando preço e transparência são analisados juntos."], ["Use o ranking como atalho", "A página de Creatina mostra produtos avaliados pelo Índice SupleScore. Consulte a nota, abra os detalhes e compare as opções antes de comprar."]], link: "/creatina", linkText: "Ver ranking de creatina" },
  "como-comparar-whey-protein-corretamente": { title: "Como comparar Whey Protein corretamente", description: "Um método simples para comparar whey protein por proteína, porção, preço e custo-benefício.", intro: "Whey protein não deve ser comparado apenas pelo preço do pacote. A forma mais justa é olhar para a porção, a quantidade de proteína e o custo que realmente será pago por uso.", sections: [["Padronize a porção", "Anote o tamanho da porção de cada produto. Embalagens maiores nem sempre entregam melhor valor se a porção também for maior."], ["Compare o produto, não só a marca", "Leia a composição e observe a quantidade de proteína informada. O catálogo do SupleScore permite abrir páginas individuais e conferir os dados de cada opção."], ["Veja a comparação completa", "Use a categoria de Whey Protein para navegar entre os produtos publicados e encontrar uma opção coerente com seu orçamento e objetivo."]], link: "/categorias/whey-protein", linkText: "Comparar whey protein" },
  "pre-treino-o-que-importa-antes-de-comprar": { title: "Pré-Treino: o que realmente importa antes de comprar", description: "O que observar na fórmula, na dose e no custo antes de escolher um pré-treino.", intro: "Antes de comprar um pré-treino, vale entender a fórmula e comparar o custo por dose. Assim a escolha fica baseada no que está no rótulo, e não apenas em promessas de marketing.", sections: [["Leia a fórmula", "Confira os ingredientes e suas quantidades por porção. Produtos diferentes podem ter propostas e concentrações diferentes."], ["Calcule o custo por uso", "Divida o preço pela quantidade de porções. Essa conta ajuda a comparar embalagens de tamanhos diferentes e revela o custo real da rotina."], ["Compare opções avaliadas", "Na categoria de Pré-Treino do SupleScore você encontra produtos publicados e pode acessar seus detalhes para tomar uma decisão mais informada."]], link: "/categorias/pre-treino", linkText: "Ver ranking de pré-treino" },
} as const;

export function generateStaticParams() { return Object.keys(articles).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const article = articles[slug as keyof typeof articles]; return article ? buildMetadata({ title: article.title, description: article.description, path: `/artigos/${slug}` }) : {}; }

export default async function ArticlePage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const article = articles[slug as keyof typeof articles]; if (!article) notFound(); return <><JsonLd data={breadcrumbSchema([{ label: "Início", href: "/" }, { label: "Artigos", href: "/artigos" }, { label: article.title, href: `/artigos/${slug}` }])} /><PageHeader eyebrow="Guia SupleScore" title={article.title} description={article.description} /><Section><article className="prose prose-neutral max-w-3xl"><p className="lead">{article.intro}</p>{article.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}<p><Link className="font-semibold text-primary hover:underline" href={article.link}>{article.linkText} →</Link></p></article></Section></>; }
